version: '3.1'
services:
  mongo:
    image: mongo:4
    container_name: 'salt-mongodb'
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: --smallfiles --logpath=/dev/null